version: '3'
services:
  netdata:
    image: netdata/netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '19999:19999'
  influxdb:
    image: influxdb
    volumes:
      - 'influxdb-storage:/var/lib/influxdb'
    ports:
      - '127.0.0.1:8086:8086'
    restart: always
  grafana:
    image: grafana/grafana
    volumes:
      - 'grafana-storage:/var/lib/grafana'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - '3000:3000'
    restart: always
  netdata-grabber:
    image: ghcr.io/terorie/netdata-influx:main
    environment:
      - NI_INFLUX_ADDR=http://influxdb:8086
      - NI_INFLUX_DB=netdata
      - NI_NETDATA_API=https://netdata:19999/api
      - NI_HOST_TAG=localhost-main
      - NI_CHARTS=system.cpu system.net system.pgpgio
    restart: always
volumes:
  grafana-storage:
  influxdb-storage:
