on: [ push, pull_request ]
name: go vet
jobs:
  unit_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Test
      run: go vet .
